artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_train_path: Data\Train.csv
  source_test_path: Data\Test.csv
  train_path: artifacts/data_ingestion/train_data.csv
  test_path: artifacts/data_ingestion/test_data.csv



data_transformation:
  root_dir: artifacts/data_transformation
  train_path: artifacts/data_ingestion/train_data.csv
  test_path: artifacts/data_ingestion/test_data.csv
  train_data: artifacts/data_transformation/train.csv
  test_data: artifacts/data_transformation/test.csv
  preprocessor: artifacts/data_transformation/preprocessor.pkl


model_trainer:
  root_dir: artifacts/model_trainer
  model_save_path: artifacts/model_trainer/model.pkl


model_tuner:
  root_dir: artifacts/model_tuner
  tuner_save_path: artifacts/model_tuner/best_model.pkl
  model_save_path: artifacts/model_trainer/model.pkl
  cv_folds: 3
  scoring: 'roc_auc'
  model_name: 'Gradient Boosting'
  n_iter: 10
  param_dist:
    Gradient Boosting:
      n_estimators: [100, 300]
      learning_rate: [0.01, 0.05]
      max_depth: [3, 5, 7]
      min_samples_leaf: [2, 5, 10]
      subsample: [0.6, 0.8, 1.0]
      min_samples_split: [2, 5, 10]
      max_features: ['sqrt', 'log2']


  model_evaluation:
    root_dir: artifacts/model_evaluation
    best_model_path: artifacts/model_tuner/best_model.pkl
    save_path: artifacts/model_evaluation/evaluation_results.json
       
                                                                                       

  